export const COUNTRY_CODE_TO_NAME: { [key: string]: string } = {
  'eg': 'Egypt',
  'us': 'USA',
  'gb': 'UK',
  'ca': 'Canada',
  'de': 'Germany',
  'lu': 'Luxembourg',
  'at': 'Austria',
  'fr': 'France',
  'be': 'Belgium',
  'es': 'Spain',
  'ch': 'Switzerland',
  'pt': 'Portugal',
  'nl': 'Netherlands',
  'is': 'Iceland',
  'ie': 'Ireland',
  'fi': 'Finland',
  'no': 'Norway',
  'dk': 'Denmark',
  'se': 'Sweden',
  'zw': 'Zimbabwe',
  'zm': 'Zambia',
  'ug': 'Uganda',
  'tz': 'Tanzania',
  'cz': 'Czech Republic',
  'rw': 'Rwanda',
  'bw': 'Botswana',
  'ng': 'Nigeria',
  'gh': 'Ghana',
  'mw': 'Malawi',
  'ci': 'Ivory Coast',
  'ke': 'Kenya',
  'ma': 'Morocco',
  'mu': 'Mauritius',
  'kr': 'Korea',
  'hu': 'Hungary',
  'pl': 'Poland',
  'ph': 'Philippines',
  'id': 'Indonesia',
  'au': 'Australia',
  'cn': 'China',
  'in': 'India',
  'za': 'South Africa',
  'pk': 'Pakistan',
  'my': 'Malaysia',
  'vn': 'Vietnam',
  'lk': 'Sri Lanka',
  'th': 'Thailand',
  'cl': 'Chile',
  'gr': 'Greece',
  'ar': 'Argentina',
  'br': 'Brazil',
  'ro': 'Romania',
  'tr': 'Turkey',
  'pe': 'Peru',
  'tw': 'Taiwan',
  'hr': 'Croatia',
  'mx': 'Mexico',
  'ae': 'United Arab Emirates',
  'hk': 'Hong Kong',
  'it': 'Italy',
  'jp': 'Japan',
  'jo': 'Jordan',
  'kw': 'Kuwait',
  'lb': 'Lebanon',
  'nz': 'New Zealand',
  'om': 'Oman',
  'qa': 'Qatar',
  'ru': 'Russia',
  'sa': 'Saudi Arabia',
  'sg': 'Singapore'
} as const;

export type CountryCode = keyof typeof COUNTRY_CODE_TO_NAME;

export const COUNTRY_NAMES = Object.values(COUNTRY_CODE_TO_NAME);
export const COUNTRY_CODES = Object.keys(COUNTRY_CODE_TO_NAME) as CountryCode[];