/**
 * Currency data for different countries
 */

// ISO codes for countries (used in API calls)
export const COUNTRY_ISO_CODES = {
  "USA": "us",
  "UK": "uk",
  "Canada": "ca",
  "Germany": "de",
  "Luxembourg": "lu",
  "Austria": "at",
  "France": "fr",
  "Netherlands": "nl",
  "Switzerland": "ch",
  "Italy": "it",
  "Spain": "es",
  "Belgium": "be",
  "Portugal": "pt",
  "Ireland": "ie",
  "Norway": "no",
  "Sweden": "se",
  "Finland": "fi",
  "Denmark": "dk",
  "Iceland": "is",
  "Russia": "ru",
  "Turkey": "tr",
  "Poland": "pl",
  "Czech Republic": "cz",
  "Hungary": "hu",
  "Greece": "gr",
  "Romania": "ro",
  "Bulgaria": "bg",
  "Croatia": "hr",
  "Slovenia": "si",
  "Serbia": "rs",
  "Cyprus": "cy",
  "Estonia": "ee",
  "Latvia": "lv",
  "Lithuania": "lt",
  "Ukraine": "ua",
  "Japan": "jp",
  "China": "cn",
  "Hong Kong": "hk",
  "Taiwan": "tw",
  "South Korea": "kr",
  "Singapore": "sg",
  "Malaysia": "my",
  "Indonesia": "id",
  "Thailand": "th",
  "Philippines": "ph",
  "Vietnam": "vn",
  "India": "in",
  "Pakistan": "pk",
  "Sri Lanka": "lk",
  "Bangladesh": "bd",
  "Australia": "au",
  "New Zealand": "nz",
  "South Africa": "za",
  "Nigeria": "ng",
  "Kenya": "ke",
  "Morocco": "ma",
  "Tunisia": "tn",
  "Egypt": "eg",
  "Botswana": "bw",
  "Rwanda": "rw",
  "Brazil": "br",
  "Mexico": "mx",
  "Argentina": "ar",
  "Chile": "cl",
  "Colombia": "co",
  "Peru": "pe",
  "Venezuela": "ve",
  "Saudi Arabia": "sa",
  "Qatar": "qa",
  "United Arab Emirates": "ae",
  "Kuwait": "kw",
  "Bahrain": "bh",
  "Oman": "om",
  "Jordan": "jo",
};

// Currency symbols for different countries
export const CURRENCY_SYMBOLS = {
  "USA": "$",
  "UK": "£",
  "Canada": "C$",
  "Germany": "€",
  "Luxembourg": "€",
  "Austria": "€",
  "France": "€",
  "Netherlands": "€",
  "Switzerland": "CHF",
  "Italy": "€",
  "Spain": "€",
  "Belgium": "€",
  "Portugal": "€",
  "Ireland": "€",
  "Norway": "kr",
  "Sweden": "kr",
  "Finland": "€",
  "Denmark": "kr",
  "Iceland": "kr",
  "Russia": "₽",
  "Turkey": "₺",
  "Poland": "zł",
  "Czech Republic": "Kč",
  "Hungary": "Ft",
  "Greece": "€",
  "Romania": "lei",
  "Bulgaria": "лв",
  "Croatia": "kn",
  "Slovenia": "€",
  "Serbia": "din",
  "Cyprus": "€",
  "Estonia": "€",
  "Latvia": "€",
  "Lithuania": "€",
  "Ukraine": "₴",
  "Japan": "¥",
  "China": "¥",
  "Hong Kong": "HK$",
  "Taiwan": "NT$",
  "South Korea": "₩",
  "Singapore": "S$",
  "Malaysia": "RM",
  "Indonesia": "Rp",
  "Thailand": "฿",
  "Philippines": "₱",
  "Vietnam": "₫",
  "India": "₹",
  "Pakistan": "₨",
  "Sri Lanka": "Rs",
  "Bangladesh": "৳",
  "Australia": "A$",
  "New Zealand": "NZ$",
  "South Africa": "R",
  "Nigeria": "₦",
  "Kenya": "KSh",
  "Morocco": "د.م.",
  "Tunisia": "د.ت",
  "Egypt": "E£",
  "Botswana": "P",
  "Rwanda": "FRw",
  "Brazil": "R$",
  "Mexico": "Mex$",
  "Argentina": "$",
  "Chile": "CLP$",
  "Colombia": "COL$",
  "Peru": "S/",
  "Venezuela": "Bs",
  "Saudi Arabia": "﷼",
  "Qatar": "QR",
  "United Arab Emirates": "د.إ",
  "Kuwait": "د.ك",
  "Bahrain": "BD",
  "Oman": "ر.ع.",
  "Jordan": "JD",};

// Map of exchange codes to their currency symbols
export const EXCHANGE_CURRENCY_SYMBOLS = {
  "US": "$",
  "LSE": "£",
  "IL": "£",
  "TO": "C$",
  "V": "C$",
  "NEO": "C$",
  "BE": "€",
  "HM": "€",
  "XETRA": "€",
  "DU": "€",
  "HA": "€",
  "MU": "€",
  "STU": "€",
  "F": "€",
  "LU": "€",
  "VI": "€",
  "PA": "€",
  "AS": "€",
  "SW": "CHF",
  "VX": "CHF",
  "MI": "€",
  "IM": "€",
  "MC": "€",
  "BC": "€",
  "BR": "€",
  "LS": "€",
  "IR": "€",
  "OL": "kr",
  "ST": "kr",
  "HE": "€",
  "CO": "kr",
  "IC": "kr",
  "MCX": "₽",
  "IS": "₺",
  "WAR": "zł",
  "PR": "Kč",
  "BD": "Ft",
  "AT": "€",
  "BX": "lei",
  "SO": "лв",
  "ZSE": "kn",
  "LJE": "€",
  "BELEX": "din",
  "CY": "€",
  "TL": "€",
  "RG": "€",
  "VSE": "€",
  "UX": "₴",
  "T": "¥",
  "OSA": "¥",
  "NSE": "¥",
  "SAP": "¥",
  "FSE": "¥",
  "SHG": "¥",
  "SHE": "¥",
  "SZE": "¥",
  "HK": "HK$",
  "TW": "NT$",
  "TWO": "NT$",
  "KO": "₩",
  "KQ": "₩",
  "SI": "S$",
  "KLSE": "RM",
  "JK": "Rp",
  "BK": "฿",
  "PSE": "₱",
  "HOSE": "₫",
  "HNX": "₫",
  "BSE": "₹",
  "NSE": "₹",
  "KAR": "₨",
  "CSE": "Rs",
  "DSE": "৳",
  "AU": "A$",
  "NZ": "NZ$",
  "JSE": "R",
  "NGSE": "₦",
  "XNAI": "KSh",
  "CASA": "د.م.",
  "BVMT": "د.ت",
  "EGX": "E£",
  "XBOT": "P",
  "RSE": "FRw",
  "BVMF": "R$",
  "MX": "Mex$",
  "BA": "$",
  "SN": "CLP$",
  "BVC": "COL$",
  "LIM": "S/",
  "CCS": "Bs",
  "SR": "﷼",
  "QA": "QR",
  "ADX": "د.إ",
  "DFM": "د.إ",
  "KW": "د.ك",
  "BAX": "BD",
  "MSM": "ر.ع.",
  "AMMAN": "JD",
};

/**
 * Get the currency symbol for a country
 */
export function getCurrencySymbol(country, exchange) {
  // First try to get currency from exchange code
  if (exchange && EXCHANGE_CURRENCY_SYMBOLS[exchange]) {
    return EXCHANGE_CURRENCY_SYMBOLS[exchange];
  }
  
  // Then try to get currency from country name
  if (country && CURRENCY_SYMBOLS[country]) {
    return CURRENCY_SYMBOLS[country];
  }
  
  // Default to USD
  return "$";
}
